import os
import tempfile
import serial
import requests
import json
import time
import threading
import pandas as pd
import numpy as np
import glob
import re
from fastapi import FastAPI, BackgroundTasks, Request
import uvicorn
from xgboost import XGBClassifier
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
import micromlgen
from threading import Lock
training_lock = Lock()
# --- DIRECTORY SETUP ---
temp_dir = os.path.join(os.getcwd(), "xgb_tmp")
if not os.path.exists(temp_dir):
    os.makedirs(temp_dir)

os.environ["TMPDIR"] = temp_dir
os.environ["TEMP"] = temp_dir
os.environ["TMP"] = temp_dir
tempfile.tempdir = temp_dir

# --- CONFIGURATION ---
SERIAL_PORT = '/dev/ttyACM0'  # Adjust as needed for your system
BAUD_RATE = 115200
DATA_STORAGE = "new_imu_data.csv"
EXEMPLAR_PREFIX = "exemplars_v"
RETRAIN_THRESHOLD = 50 
CLOUD_PORT = 8080 

# Global state
current_label = 4 
is_retraining = False
increment_version_next_run = False # Set to True when starting a new machine/dataset

app = FastAPI()

def get_latest_exemplar_file():
    """Finds the exemplar file with the highest version number and handles initial rename."""
    # Professional Rename: CWRU Baseline becomes v1
    if os.path.exists("cwru_exemplars.csv") and not glob.glob(f"{EXEMPLAR_PREFIX}*.csv"):
        os.rename("cwru_exemplars.csv", f"{EXEMPLAR_PREFIX}1.csv")
        print("[SETUP] Professionalized: cwru_exemplars.csv -> exemplars_v1.csv")

    files = glob.glob(f"{EXEMPLAR_PREFIX}*.csv")
    if not files:
        return None
    
    files.sort(key=lambda f: int(re.search(r'v(\d+)', os.path.basename(f)).group(1)))    
    return files[-1]

def manage_exemplar_memory(latest_path, new_data_path, samples_per_class=50):
    """Updates the exemplar file. Increments version only if a new dataset/machine is triggered."""
    global increment_version_next_run
    try:
        current_version = int(re.search(r'v(\d+)', latest_path).group(1))
        
        # Decide if we overwrite or create a new file
        # Rule: Never overwrite v1 (baseline). If we are adding to a dataset, update current. 
        # If 'new' was typed, or we are moving away from v1, create next version.
        if latest_path == f"{EXEMPLAR_PREFIX}1.csv" or increment_version_next_run:
            target_path = f"{EXEMPLAR_PREFIX}{current_version + 1}.csv"
            print(f"[MEMORY] Creating NEW version: {target_path}")
            increment_version_next_run = False # Reset flag
        else:
            target_path = latest_path
            print(f"[MEMORY] Updating CURRENT version: {target_path}")
        
        old_df = pd.read_csv(latest_path)
        new_df = pd.read_csv(new_data_path)
        
        new_classes = new_df['label'].unique()
        # Keep old knowledge, but replace classes we are currently refining
        old_df = old_df[~old_df['label'].isin(new_classes)]
        
        updated_exemplars = [old_df]
        for cls in new_classes:
            cls_data = new_df[new_df['label'] == cls]
            selection = cls_data.tail(samples_per_class)
            updated_exemplars.append(selection)

        final_df = pd.concat(updated_exemplars, ignore_index=True)
        final_df.to_csv(target_path, index=False)
        return target_path
        
    except Exception as e:
        print(f"[MEMORY ERROR] Memory update failed: {e}")
        return latest_path

def run_cil_pipeline(new_data_path):
    global is_retraining
    is_retraining = True
    
    latest_exemplar = get_latest_exemplar_file()
    if not latest_exemplar:
        print("[CIL ERROR] Base exemplars (v1) not found!")
        is_retraining = False
        return

    print("\n" + "="*50)
    print(f"[CIL ENGINE] >>> EVOLVING MODEL (Base: {latest_exemplar}) <<<")
    print("="*50)
    
    try:
        # 1. Load and Combine
        old_df = pd.read_csv(latest_exemplar)
        new_df = pd.read_csv(new_data_path)
        
        X_old, y_old = old_df.iloc[:, :11].values, old_df['label'].values
        X_new, y_new = new_df.iloc[:, :11].values, new_df['label'].values
        
        X_combined = np.vstack([X_old, X_new])
        y_combined = np.concatenate([y_old, y_new])
        
        # --- SHUFFLE ---
        X_combined, y_combined = shuffle(X_combined, y_combined, random_state=42)
        print("[CIL] Dataset shuffled for training stability.")

        # 2. Unified Scaling
        scaler = StandardScaler().fit(X_combined)
        X_scaled = scaler.transform(X_combined)
        
        # 3. Export scaler.h
        means = ", ".join([str(round(x, 8)) for x in scaler.mean_])
        stdvs = ", ".join([str(round(x, 8)) for x in np.sqrt(scaler.var_)])
        with open("scaler.h", "w") as f:
            f.write(f"// Generated by CIL Cloud\n")
            f.write(f"float mean[11] = {{{means}}};\n")
            f.write(f"float stdv[11] = {{{stdvs}}};\n")
        
        # 4. Train XGBoost
        print(f"[CIL] Training XGBoost for {len(np.unique(y_combined))} classes...")
        xgb = XGBClassifier(n_estimators=15, max_depth=3, learning_rate=0.1, n_jobs=-1, tree_method='hist',random_state=42)
        xgb.fit(X_scaled, y_combined)
        
        # 5. Update SVM
        print(f"[CIL] Expanding SVM Anomaly Boundary...")
        svm = OneClassSVM(kernel='rbf', nu=0.025, gamma=0.09).fit(X_scaled)
        
        # 6. Export Headers
        with open("classifier.h", "w") as f: f.write(micromlgen.port(xgb, class_name="XGBClassifier"))
        with open("svm.h", "w") as f: f.write(micromlgen.port(svm, class_name="SVMClassifier"))
            
        print("\n" + "#"*50)
        print("SUCCESS: C++ HEADERS UPDATED")
        print("#"*50 + "\n")
        
        # 7. MANAGE MEMORY (Update existing or increment version)
        manage_exemplar_memory(latest_exemplar, new_data_path)
        
        # 8. CLEAR BUFFER
        if os.path.exists(new_data_path):
            os.remove(new_data_path)
            print("[CIL] Buffer cleared. Ready for next class.")
        
    except Exception as e: 
        print(f"\n[CIL ERROR] Training failed: {e}")
    finally:
        is_retraining = False
        if training_lock.locked():
            training_lock.release()

@app.post("/upload_anomaly")
async def upload_anomaly(request: Request, background_tasks: BackgroundTasks):
    global current_label, is_retraining
    data = await request.json()
    features = data.get("features")
    if not features or len(features) != 11:
        return {"status": "invalid_features"}
    
    
    cols = [f'f{i}' for i in range(11)] + ['label']
    df = pd.DataFrame([features + [current_label]], columns=cols)
    
    file_exists = os.path.exists(DATA_STORAGE)
    df.to_csv(DATA_STORAGE, mode='a', index=False, header=not file_exists)
    
    full_df = pd.read_csv(DATA_STORAGE)
    count = len(full_df[full_df['label'] == current_label])
    
    if count < RETRAIN_THRESHOLD:
        print(f"| Label: {current_label} | Progress: {count}/{RETRAIN_THRESHOLD} |", end="\r")
    elif count >= RETRAIN_THRESHOLD:
        print(f"\n[DONE] Sufficient data for Class {current_label}! Starting Cloud Retraining...")
        if not is_retraining and training_lock.acquire(blocking=False):
            threading.Thread(target=run_cil_pipeline, args=(DATA_STORAGE,), daemon=True).start()
    
    return {"status": "ok"}

def keyboard_control():
    global current_label, increment_version_next_run
    time.sleep(1)
    print("\n" + "="*40)
    print("COMMANDS:")
    print("4, 5, 6 : Switch IMU Labels")
    print("'new'   : Start new version (v3, v4...) for new machine")
    print("="*40)
    while True:
        try:
            val = input().strip().lower()
            if val in ['4', '5', '6']:
                current_label = int(val)
                print(f">>> TEACHING MODE: CLASS {current_label}")
            elif val == 'new':
                increment_version_next_run = True
                print(">>> SYSTEM READY: Next training session will create a NEW version file.")
        except EOFError: break

def serial_bridge():
    print(f"[SERIAL] Attempting to connect to {SERIAL_PORT}...")
    ser = None
    while ser is None:
        try:
            ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=0.1)
            print(f"[SERIAL] Connection established!")
        except Exception:
            time.sleep(2)

    while True:
        try:
            if ser.in_waiting > 0:
                line = ser.readline().decode('utf-8', errors='ignore').strip()
                if line.startswith("raw:"):
                    feats = [float(v) for v in line.replace("raw:", "").split(",")]
                    requests.post(f"http://127.0.0.1:{CLOUD_PORT}/upload_anomaly", json={"features": feats})
        except Exception: pass

if __name__ == "__main__":
    get_latest_exemplar_file() # Initial setup
    threading.Thread(target=serial_bridge, daemon=True).start()
    threading.Thread(target=keyboard_control, daemon=True).start()
    uvicorn.run(app, host="127.0.0.1", port=CLOUD_PORT, log_level="warning")